### ISSUE TITLE
[MFC-7820N] throws pysnmp.proto.errind.RequestTimedOut: No SNMP response received before timeout

### ISSUE THREAD

**Issue by Wikinaut** [CauldronDevelopmentLLC/oh-brother#13] opened 2017-02-28 07:29 UTC
When trying your code on my MFC-7820N, the output is:

```
$ /oh-brother.py xxx.xxx.xxx.xxx
Getting SNMP data from printer at xxx.xxx.xxx.xxx...
done
Traceback (most recent call last):
  File "./oh-brother.py", line 98, in <module>
    if error: raise error
pysnmp.proto.errind.RequestTimedOut: No SNMP response received before timeout
```

Perhaps the timeout can be caught better. 

I don't know, why my old MFC is not responding, perhaps this model is simply too old and does not support the protocol? I have no idea.

**Comment by jcoffland** [comment] 2017-02-28 09:06
Have you set the admin password on the printer?  This is a possible duplicate of #9

**Comment by Wikinaut** [comment] 2017-02-28 09:13
Good catch, at first, I had not, but then, yes. Yes, there are passwords. 

This device has a 
* a user "admin" with an admin password ; and
* a user "user" with a user password.

![20170228-10 12 29_auswahl](https://cloud.githubusercontent.com/assets/1151915/23398880/7cef73aa-fd9e-11e6-9ca9-5cff1662bac6.png)

Both passwords are different to the default passwords, of course.

**Closed** 2019-07-29 21:09 UTC
